### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by stetelepta** [neo4j/graph-data-science-client#565]
**Describe the bug**
The latest graph data science client (1.8) depends on `pyarrow >= 4.0, < 15.0` which includes the vulnerable versions 0.14.0 to 14.0.0 (severity: critical) as described here:

* https://arrow.apache.org/security/
* https://www.cve.org/CVERecord?id=CVE-2023-47248

Proposed mitigation is to make sure to use pyarrow version 14.0.1 or greater.

Would be great if you can update the requirements, as we currently cannot install package due to policy violations because of this vulnerability.

**Comment by soerenreichardt** [comment]
Hello @stetelepta,
we did shrink the available versions now, but not as narrow as you suggested, as we might have customers that use older versions of pyarrow. 
Pip will automatically install the newest version of pyarrow unless you specify otherwise. Therefore it's not clear to us why your policy doesn't allow you to use a library that lets you use a secure version of pyarrow.

**Comment by stetelepta** [comment]
Hi Sören,

Thank you, I am also not completely sure, but when it failed the scanner (Nexus) mentioned the security vulnerability. Just tried again and package is now installed successfully!
